import 'package:flutter/material.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:provider/provider.dart';

import '../../app_theme.dart';
import '../../constants.dart';
import '../../models/doctor_model.dart';
import '../../models/booking_model.dart';
import '../../providers/user_provider.dart';
import '../../services/insforge_service.dart';
import '../../services/razorpay_web_service.dart';
import '../../utils/error_helper.dart';
import '../../widgets/maa_button.dart';

class PatientBookingScreen extends StatefulWidget {
  final DoctorModel doctor;

  const PatientBookingScreen({super.key, required this.doctor});

  @override
  State<PatientBookingScreen> createState() => _PatientBookingScreenState();
}

class _PatientBookingScreenState extends State<PatientBookingScreen> {
  int _currentStep = 0; // 0 = Details, 1 = Slot Selection
  bool _processing = false;

  final _formKey = GlobalKey<FormState>();
  
  // Patient Vitals
  final _nameController = TextEditingController();
  final _ageController = TextEditingController();
  final _heightController = TextEditingController();
  final _weightController = TextEditingController();
  final _symptomsController = TextEditingController();
  String _selectedGender = 'Female';

  // Slot Selection
  DateTime? _selectedDate;
  String? _selectedTime;
  
  // Strict allowed times
  final List<String> _allowedTimes = [
    '06:00 AM',
    '07:00 AM',
    '08:00 AM',
    '09:00 AM'
  ];

  @override
  void dispose() {
    _nameController.dispose();
    _ageController.dispose();
    _heightController.dispose();
    _weightController.dispose();
    _symptomsController.dispose();
    super.dispose();
  }

  void _triggerPayment() async {
    if (!_formKey.currentState!.validate()) return;

    final user = context.read<UserProvider>().user;
    if (user == null) {
      ErrorHelper.showError(context, 'Please log in to book appointments.');
      return;
    }

    setState(() => _processing = true);

    RazorpayWebService.instance.openCheckout(
      keyId: AppConstants.razorpayKey,
      amount: 50000, // ₹500 in paise
      currency: 'INR',
      name: 'MaaCare Health',
      description: 'Consultation with ${widget.doctor.name}',
      email: user.email,
      phone: '9999999999',
      onSuccess: (paymentId) {
        if (!mounted) return;
        setState(() {
          _processing = false;
          _currentStep = 1; // Move to Slot Selection
        });
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Payment Successful! Please schedule your slot. ✅'),
            backgroundColor: MaaColors.success,
          ),
        );
      },
      onFailed: (error) {
        if (!mounted) return;
        setState(() => _processing = false);
        ErrorHelper.showError(context, 'Payment failed or cancelled.');
      },
      onDismiss: () {
        if (!mounted) return;
        setState(() => _processing = false);
      },
    );
  }

  void _confirmBooking() async {
    if (_selectedDate == null || _selectedTime == null) {
      ErrorHelper.showError(context, 'Please select both Date and Time constraints.');
      return;
    }

    setState(() => _processing = true);

    final user = context.read<UserProvider>().user;

    // Bundle vitals safely into symptoms payload to avoid schema migration overhead
    final bundledSymptoms = '''
[Patient Profile]
Age: ${_ageController.text.trim()} yrs
Gender: $_selectedGender
Height: ${_heightController.text.trim()} cm
Weight: ${_weightController.text.trim()} kg

[Symptoms / Reason]
${_symptomsController.text.trim()}
    ''';

    final booking = BookingModel(
      id: '', // Generated by backend
      userId: user!.id,
      doctorId: widget.doctor.id,
      patientName: _nameController.text.trim(),
      symptoms: '$_selectedTime\n\n${bundledSymptoms.trim()}',
      appointmentDate: _selectedDate!, 
      status: 'scheduled',
      paymentStatus: 'paid',
      meetingLink: '',
      amount: '₹500', // Fixed premium fee
      createdAt: DateTime.now(),
    );

    final success = await InsForgeService.instance.bookAppointment(booking);

    if (!mounted) return;
    setState(() => _processing = false);

    if (success) {
      // Show Success Dialog
      showDialog(
        context: context,
        barrierDismissible: false,
        builder: (_) => AlertDialog(
          backgroundColor: MaaColors.cardDark,
          title: const Text('🎉 Appointment Confirmed',
              style: TextStyle(color: MaaColors.white)),
          content: Text(
            'Your consultation with ${widget.doctor.name} is successfully booked for $_selectedTime on ${_selectedDate!.day}/${_selectedDate!.month}/${_selectedDate!.year}.\n\nA secure Video Meeting link will be generated shortly.',
            style: const TextStyle(color: MaaColors.textMuted),
          ),
          actions: [
            TextButton(
              onPressed: () {
                Navigator.pop(context); // Close dialog
                Navigator.pop(context); // Go back out to consult list
              },
              child: const Text('Return to Dashboard',
                  style: TextStyle(color: MaaColors.pink)),
            )
          ],
        ),
      );
    } else {
      ErrorHelper.showError(context, 'Failed to save appointment. Please contact support.');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(_currentStep == 0 ? 'Patient Details' : 'Select Slot'),
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(24),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Header Indicator
              Row(
                children: [
                  _buildStepIndicator(0, 'Details & Payment'),
                  Expanded(
                      child: Container(
                          height: 2,
                          color: _currentStep > 0
                              ? MaaColors.pink
                              : MaaColors.textGrey.withValues(alpha: 0.2))),
                  _buildStepIndicator(1, 'Pick Slot 🗓️'),
                ],
              ),
              const SizedBox(height: 32),

              if (_currentStep == 0) _buildDetailsForm() else _buildSlotSelection(),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildStepIndicator(int stepIndex, String label) {
    final isActive = _currentStep >= stepIndex;
    return Column(
      children: [
        Container(
          width: 32,
          height: 32,
          decoration: BoxDecoration(
            shape: BoxShape.circle,
            color: isActive ? MaaColors.pink : MaaColors.cardDark,
            border: Border.all(
                color: isActive ? Colors.transparent : MaaColors.pink),
          ),
          child: Center(
            child: Icon(
              stepIndex == 0 ? Icons.person : Icons.access_time_rounded,
              size: 16,
              color: isActive ? MaaColors.white : MaaColors.pink,
            ),
          ),
        ),
        const SizedBox(height: 8),
        Text(
          label,
          style: TextStyle(
            fontSize: 12,
            fontWeight: FontWeight.w600,
            color: isActive ? MaaColors.white : MaaColors.textGrey,
          ),
        ),
      ],
    );
  }

  Widget _buildDetailsForm() {
    return Form(
      key: _formKey,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          Text('Patient Information',
              style: GoogleFonts.poppins(
                  fontSize: 20,
                  fontWeight: FontWeight.bold,
                  color: MaaColors.white)),
          const SizedBox(height: 20),
          _buildTextField(_nameController, 'Full Name', Icons.person),
          _buildTextField(_ageController, 'Age', Icons.cake, isNumber: true),
          
          Padding(
            padding: const EdgeInsets.symmetric(vertical: 8),
            child: DropdownButtonFormField<String>(
              value: _selectedGender,
              items: ['Female', 'Male', 'Other']
                  .map((g) => DropdownMenuItem(value: g, child: Text(g)))
                  .toList(),
              onChanged: (v) => setState(() => _selectedGender = v!),
              decoration: InputDecoration(
                labelText: 'Gender',
                labelStyle: const TextStyle(color: MaaColors.textMuted),
                prefixIcon: const Icon(Icons.wc, color: MaaColors.pink),
                filled: true,
                fillColor: MaaColors.cardDark,
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(12),
                  borderSide: BorderSide.none,
                ),
              ),
              dropdownColor: MaaColors.background,
              style: const TextStyle(color: MaaColors.white),
            ),
          ),

          Row(
            children: [
              Expanded(
                child: _buildTextField(_heightController, 'Height (cm)', Icons.height, isNumber: true),
              ),
              const SizedBox(width: 16),
              Expanded(
                child: _buildTextField(_weightController, 'Weight (kg)', Icons.monitor_weight, isNumber: true),
              ),
            ],
          ),
          
          _buildTextField(_symptomsController, 'Reasons / Symptoms', Icons.medical_services, maxLines: 3),
          
          const SizedBox(height: 32),
          
          MaaButton(
            label: 'Proceed to Payment (₹500)',
            icon: Icons.lock_rounded,
            isLoading: _processing,
            onPressed: _triggerPayment,
          ),
          const SizedBox(height: 12),
          const Center(
            child: Text(
              'Secured by Razorpay. SSL Encrypted🔒',
              style: TextStyle(color: MaaColors.textGrey, fontSize: 12),
            ),
          ),
        ],
      ).animate().fadeIn().slideY(begin: 0.1, end: 0),
    );
  }

  Widget _buildSlotSelection() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        Text('Secure a Consultation Slot',
            style: GoogleFonts.poppins(
                fontSize: 20,
                fontWeight: FontWeight.bold,
                color: MaaColors.white)),
        const SizedBox(height: 4),
        const Text(
            'Doctor available between 6:00 AM - 9:00 AM.',
            style: TextStyle(color: MaaColors.textGrey, fontSize: 13)),
        const SizedBox(height: 24),
        
        // Date Picker Request
        GestureDetector(
          onTap: () async {
            final now = DateTime.now();
            final picked = await showDatePicker(
              context: context,
              initialDate: _selectedDate ?? now,
              firstDate: now,
              lastDate: now.add(const Duration(days: 30)),
              builder: (context, child) {
                return Theme(
                  data: Theme.of(context).copyWith(
                    colorScheme: const ColorScheme.dark(
                      primary: MaaColors.pink,
                      onPrimary: MaaColors.white,
                      surface: MaaColors.cardDark,
                      onSurface: MaaColors.white,
                    ),
                  ),
                  child: child!,
                );
              },
            );
            if (picked != null) {
              setState(() => _selectedDate = picked);
            }
          },
          child: Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: MaaColors.cardDark,
              borderRadius: BorderRadius.circular(12),
              border: Border.all(color: MaaColors.pink.withValues(alpha: 0.3)),
            ),
            child: Row(
              children: [
                const Icon(Icons.calendar_month, color: MaaColors.pink),
                const SizedBox(width: 12),
                Text(
                  _selectedDate == null 
                  ? 'Tap to select Date' 
                  : '${_selectedDate!.day}/${_selectedDate!.month}/${_selectedDate!.year}',
                  style: TextStyle(
                    color: _selectedDate == null ? MaaColors.textMuted : MaaColors.white,
                    fontSize: 16,
                  ),
                ),
              ],
            ),
          ),
        ),
        
        const SizedBox(height: 24),
        const Text('Select Time', style: TextStyle(color: MaaColors.white, fontWeight: FontWeight.bold)),
        const SizedBox(height: 12),
        
        Wrap(
          spacing: 12,
          runSpacing: 12,
          children: _allowedTimes.map((time) {
            final isSelected = _selectedTime == time;
            return GestureDetector(
              onTap: () => setState(() => _selectedTime = time),
              child: Container(
                padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 12),
                decoration: BoxDecoration(
                  color: isSelected ? MaaColors.pink : MaaColors.cardDark,
                  borderRadius: BorderRadius.circular(12),
                  border: Border.all(
                    color: isSelected ? MaaColors.pink : MaaColors.white.withValues(alpha: 0.1),
                  ),
                ),
                child: Text(
                  time,
                  style: TextStyle(
                    color: isSelected ? MaaColors.white : MaaColors.textMuted,
                    fontWeight: isSelected ? FontWeight.bold : FontWeight.normal,
                  ),
                ),
              ),
            );
          }).toList(),
        ),

        const SizedBox(height: 48),

        MaaButton(
          label: 'Confirm Final Booking',
          icon: Icons.check_circle_rounded,
          isLoading: _processing,
          onPressed: _confirmBooking,
        ),
      ],
    ).animate().fadeIn().slideX(begin: 0.1, end: 0);
  }

  Widget _buildTextField(
    TextEditingController controller,
    String label,
    IconData icon, {
    bool isNumber = false,
    int maxLines = 1,
  }) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 8),
      child: TextFormField(
        controller: controller,
        keyboardType: isNumber ? TextInputType.number : TextInputType.text,
        maxLines: maxLines,
        style: const TextStyle(color: MaaColors.white),
        decoration: InputDecoration(
          labelText: label,
          labelStyle: const TextStyle(color: MaaColors.textMuted),
          prefixIcon: Icon(icon, color: MaaColors.pink),
          filled: true,
          fillColor: MaaColors.cardDark,
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12),
            borderSide: BorderSide.none,
          ),
          focusedBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12),
            borderSide: const BorderSide(color: MaaColors.pink),
          ),
        ),
        validator: (v) => v!.isEmpty ? 'Field required' : null,
      ),
    );
  }
}
